---
title: "446 a1 r"
output: pdf_document
---
```{r}
library(readr)
library(BondValuation)
library(rlist)
library(jrvFinance)
library(tidyverse)
library(ggplot2)
library(nleqslv)
A1_python <- read_csv("A1 python.csv")
A1_python <- A1_python[order(A1_python$`month until maturity`),]
```




```{r}
datelist = c("2023-01-16","2023-01-17","2023-01-18","2023-01-19","2023-01-20","2023-01-23","2023-01-24","2023-01-25","2023-01-26","2023-01-27")
a = c()
for (i in 1:10){
  a[i] <- bond.yield(settle = as.Date(A1_python$`issue date`[i]), mature = as.Date(A1_python$`maturity date`[i]),coupon = A1_python$coupon[i], freq = 2, price = A1_python$`2023-01-16`[i],convention = "30/360")
}
A1_python["1-16"] <- a 

a = c()
for (i in 1:10){
  a[i] <- bond.yield(settle = as.Date(A1_python$`issue date`[i]), mature = as.Date(A1_python$`maturity date`[i]),coupon = A1_python$coupon[i], freq = 2, price = A1_python$`2023-01-17`[i],convention = "30/360")
  }
A1_python["1-17"] <- a 

a = c()
for (i in 1:10){
  a[i] <- bond.yield(settle = as.Date(A1_python$`issue date`[i]), mature = as.Date(A1_python$`maturity date`[i]),coupon = A1_python$coupon[i], freq = 2, price = A1_python$`2023-01-18`[i],convention = "30/360")
  }
A1_python["1-18"] <- a 

a = c()
for (i in 1:10){
  a[i] <- bond.yield(settle = as.Date(A1_python$`issue date`[i]), mature = as.Date(A1_python$`maturity date`[i]),coupon = A1_python$coupon[i], freq = 2, price = A1_python$`2023-01-19`[i],convention = "30/360")
  }
A1_python["1-19"] <- a 

a = c()
for (i in 1:10){
  a[i] <- bond.yield(settle = as.Date(A1_python$`issue date`[i]), mature = as.Date(A1_python$`maturity date`[i]),coupon = A1_python$coupon[i], freq = 2, price = A1_python$`2023-01-20`[i],convention = "30/360")
  }
A1_python["1-20"] <- a 

a = c()
for (i in 1:10){
  a[i] <- bond.yield(settle = as.Date(A1_python$`issue date`[i]), mature = as.Date(A1_python$`maturity date`[i]),coupon = A1_python$coupon[i], freq = 2, price = A1_python$`2023-01-23`[i],convention = "30/360")
  }
A1_python["1-23"] <- a 

a = c()
for (i in 1:10){
  a[i] <- bond.yield(settle = as.Date(A1_python$`issue date`[i]), mature = as.Date(A1_python$`maturity date`[i]),coupon = A1_python$coupon[i], freq = 2, price = A1_python$`2023-01-24`[i],convention = "30/360")
  }
A1_python["1-24"] <- a 

a = c()
for (i in 1:10){
  a[i] <- bond.yield(settle = as.Date(A1_python$`issue date`[i]), mature = as.Date(A1_python$`maturity date`[i]),coupon = A1_python$coupon[i], freq = 2, price = A1_python$`2023-01-25`[i],convention = "30/360")
  }
A1_python["1-25"] <- a 

a = c()
for (i in 1:10){
  a[i] <- bond.yield(settle = as.Date(A1_python$`issue date`[i]), mature = as.Date(A1_python$`maturity date`[i]),coupon = A1_python$coupon[i], freq = 2, price = A1_python$`2023-01-26`[i],convention = "30/360")
  }
A1_python["1-26"] <- a 

a = c()
for (i in 1:10){
  a[i] <- bond.yield(settle = as.Date(A1_python$`issue date`[i]), mature = as.Date(A1_python$`maturity date`[i]),coupon = A1_python$coupon[i], freq = 2, price = A1_python$`2023-01-27`[i],convention = "30/360")
  }
A1_python["1-27"] <- a 

a = c()
for (i in 1:10){
  a[i] <- bond.yield(settle = as.Date(A1_python$`issue date`[i]), mature = as.Date(A1_python$`maturity date`[i]),coupon = A1_python$coupon[i], freq = 2, price = A1_python$`2023-01-30`[i],convention = "30/360")
  }
A1_python["1-30"] <- a 



new <- data.frame(dates = c(rep("1.16",10),rep("1.17",10),rep("1.18",10),rep("1.19",10),rep("1.20",10),rep("1.23",10),rep("1.24",10),rep("1.25",10),rep("1.26",10),rep("1.27",10),rep("1.30",10)),ytm = c(A1_python$`1-16`,A1_python$`1-17`,A1_python$`1-18`,A1_python$`1-19`,A1_python$`1-20`,A1_python$`1-23`,A1_python$`1-24`,A1_python$`1-25`,A1_python$`1-26`,A1_python$`1-27`,A1_python$`1-30`),bond = rep(A1_python$`bond name`,11),year_until_maturity = rep(A1_python$`year until maturity`,11))



ytm1 <- A1_python[,22:31]
year <- seq(0.5,5,0.5)
plot(year,t(ytm1[,1]),type = 'l', xlab = 'Year', ylab = 'Yield to Maturity', main = 'YTM curve',col='red', ylim=c(0.015,0.03))
lines(year,t(ytm1[,2]),col=1,lty=1,type = 'l')
lines(year,t(ytm1[,3]),col=2,lty=1,type = 'l')
lines(year,t(ytm1[,4]),col=3,lty=1,type = 'l')
lines(year,t(ytm1[,5]),col=4,lty=1,type = 'l')
lines(year,t(ytm1[,6]),col=5,lty=1,type = 'l')
lines(year,t(ytm1[,7]),col=6,lty=1,type = 'l')
lines(year,t(ytm1[,8]),col=7,lty=1,type = 'l')
lines(year,t(ytm1[,9]),col=8,lty=1,type = 'l')
lines(year,t(ytm1[,10]),col=9,lty=1,type = 'l')
legend('topleft', legend=datelist, col=c("red","1", "2", "3", "4", "5", "6", "7","8","9"), lty=1, cex=0.5)
```

```{r}
for (h in 0:11){
  l = c()
  for (j in 1:10){
    i = 0
    if (A1_python[j,6]<6){
      i = 0
    } else {
      i = as.numeric(floor(A1_python[j,6]/6))
    }
    r = c(as.numeric(-A1_python[j,9+h]),rep(A1_python$coupon[j]*100,i),100)
    rate = irr(r,c(-1,1),cf.freq = 2,comp.freq = Inf)
    l <- append(l,rate)
  }
  A1_python[,32+h] = l
}


datelist = c("2023-01-16","2023-01-17","2023-01-18","2023-01-19","2023-01-20","2023-01-23","2023-01-24","2023-01-25","2023-01-26","2023-01-27")
# construct an empty dirty price table
dirty_price <- matrix(nrow = 10, ncol = 10)
# calculate the dirty price based on close price
for (i in c(1:10)) {
  for (j in c(1:10)) {
    dirty_price[i,j] <- bond.TCF(datelist[i], as.Date(A1_python$`maturity date`[j]), A1_python$coupon[j], freq = 2)$accrued
  }
}



ytm1 <- A1_python[,33:42]
year <- seq(0.5,5,0.5)
plot(year,t(ytm1[,1]),type = 'l', xlab = 'Year', ylab = 'spot rate', main = 'spot curve',col='red', ylim=c(0.013,0.021))
lines(year,t(ytm1[,2]),col=1,lty=1,type = 'l')
lines(year,t(ytm1[,3]),col=2,lty=1,type = 'l')
lines(year,t(ytm1[,4]),col=3,lty=1,type = 'l')
lines(year,t(ytm1[,5]),col=4,lty=1,type = 'l')
lines(year,t(ytm1[,6]),col=5,lty=1,type = 'l')
lines(year,t(ytm1[,7]),col=6,lty=1,type = 'l')
lines(year,t(ytm1[,8]),col=7,lty=1,type = 'l')
lines(year,t(ytm1[,9]),col=8,lty=1,type = 'l')
lines(year,t(ytm1[,10]),col=9,lty=1,type = 'l')



```


```{r}
#forward
# construct an empty forward rate table
forward_rate <- data.frame()
# update the forward rate
for (i in c(1:4)){
  for (j in c(1:10)){
    # calculate the spot rate for 1 year
    spot_1=(1+ytm1[2+2*i,j]/2)^(2+2*i)
    # calculate the spot rate for n years
    spot_n=(1+ytm1[2*i,j]/2)^(2*i)
    # calculate the forward rate
    forward_rate[j,i]=2*((spot_1/spot_n)^(0.5)-1)
  }
}

# plot the forward rates for different dates
plot(c(2,3,4,5), forward_rate[1,], type = 'l',main = "1-Year Forward Curve", xlab = "Time To Maturity (yrs)", ylab = "Forward Rate", ylim = c(0.01,0.02))
lines(c(2,3,4,5), forward_rate[2,],type = 'l',lwd = 1.0, col='red')
lines(c(2,3,4,5), forward_rate[3,],type = 'l',lwd = 1.0, col='green')
lines(c(2,3,4,5), forward_rate[4,],type = 'l',lwd = 1.0, col='blue')
lines(c(2,3,4,5), forward_rate[5,],type = 'l',lwd = 1.0, col='lightblue')
lines(c(2,3,4,5), forward_rate[6,],type = 'l',lwd = 1.0, col='brown')
lines(c(2,3,4,5), forward_rate[7,],type = 'l',lwd = 1.0, col='orange')
lines(c(2,3,4,5), forward_rate[8,],type = 'l',lwd = 1.0, col='grey')
lines(c(2,3,4,5), forward_rate[9,],type = 'l',lwd = 1.0, col='darkblue')
lines(c(2,3,4,5), forward_rate[10,],type = 'l',lwd = 1.0, col='yellowgreen')

```









```{r}
# spot for bond 1
for (i in 1:10){
  fun <- function (x) 100*exp(-x*5/6)-as.numeric(A1_python[1,9+i])
  uni <- uniroot(fun, c(0, 8))$root
  A1_python[1,32+i] <- uni
}

# spot for bond 2
for (i in 1:10){
  c = 100*0.025/2
  fun <- function (x) 100*exp(-x*17/6)-as.numeric(A1_python[2,9+i])+c*exp(-x*5/6)+c*exp(-x*11/6)+c*exp(-x*17/6)
  uni <- uniroot(fun, c(0, 8))$root
  A1_python[2,32+i] <- uni
}

# spot for bond 3
for (i in 1:10){
  c = 100*0.015/2
  fun <- function (x) 100*exp(-x*20/6)-as.numeric(A1_python[3,9+i])+c*exp(-x*2/6)+c*exp(-x*8/6)+c*exp(-x*14/6)+c*exp(-x*20/6)
  uni <- uniroot(fun, c(0, 8))$root
  A1_python[3,32+i] <- uni
}

# spot for bond 4
for (i in 1:10){
  c = 100*0.0125/2
  fun <- function (x) 100*exp(-x*26/6)-as.numeric(A1_python[4,9+i])+c*exp(-x*2/6)+c*exp(-x*8/6)+c*exp(-x*14/6)+c*exp(-x*20/6)+c*exp(-x*26/6)
  uni <- uniroot(fun, c(0, 8))$root
  A1_python[4,32+i] <- uni
}

# spot for bond 5
for (i in 1:10){
  c = 100*0.0225/2
  fun <- function (x) 100*exp(-x*29/6)-as.numeric(A1_python[5,9+i])+c*exp(-x*5/6)+c*exp(-x*11/6)+c*exp(-x*17/6)+c*exp(-x*23/6)+c*exp(-x*29/6)
  uni <- uniroot(fun, c(0, 8))$root
  A1_python[5,32+i] <- uni
}

# spot for bond 6
for (i in 1:10){
  c = 100*0.005/2
  fun <- function (x) 100*exp(-x*32/6)-as.numeric(A1_python[6,9+i])+c*exp(-x*2/6)+c*exp(-x*8/6)+c*exp(-x*14/6)+c*exp(-x*20/6)+c*exp(-x*26/6)+c*exp(-x*32/6)
  uni <- uniroot(fun, c(0, 8))$root
  A1_python[6,32+i] <- uni
}

# spot for bond 7
for (i in 1:10){
  c = 100*0.015/2
  fun <- function (x) 100*exp(-x*41/6)-as.numeric(A1_python[7,9+i])+c*exp(-x*5/6)+c*exp(-x*11/6)+c*exp(-x*17/6)+c*exp(-x*23/6)+c*exp(-x*29/6)+c*exp(-x*35/6)+c*exp(-x*41/6)
  uni <- uniroot(fun, c(0, 8))$root
  A1_python[7,32+i] <- uni
}

# spot for bond 8
for (i in 1:10){
  c = 100*0.0125/2
  fun <- function (x) 100*exp(-x*50/6)-as.numeric(A1_python[8,9+i])+c*exp(-x*2/6)+c*exp(-x*8/6)+c*exp(-x*14/6)+c*exp(-x*20/6)+c*exp(-x*26/6)+c*exp(-x*32/6)+c*exp(-x*38/6)+c*exp(-x*44/6)+c*exp(-x*50/6)
  uni <- uniroot(fun, c(0, 8))$root
  A1_python[8,32+i] <- uni
}

# spot for bond 9
for (i in 1:10){
  c = 100*0.01/2
  fun <- function (x) 100*exp(-x*53/6)-as.numeric(A1_python[9,9+i])+c*exp(-x*5/6)+c*exp(-x*11/6)+c*exp(-x*17/6)+c*exp(-x*23/6)+c*exp(-x*29/6)+c*exp(-x*35/6)+c*exp(-x*41/6)+c*exp(-x*47/6)+c*exp(-x*53/6)
  uni <- uniroot(fun, c(0, 8))$root
  A1_python[9,32+i] <- uni
}

# spot for bond 9
for (i in 1:10){
  c = 100*0.035/2
  fun <- function (x) 100*exp(-x*62/6)-as.numeric(A1_python[10,9+i])+c*exp(-x*2/6)+c*exp(-x*8/6)+c*exp(-x*14/6)+c*exp(-x*20/6)+c*exp(-x*26/6)+c*exp(-x*32/6)+c*exp(-x*38/6)+c*exp(-x*44/6)+c*exp(-x*50/6)+c*exp(-x*56/6)+c*exp(-x*62/6)
  uni <- uniroot(fun, c(0, 8))$root
  A1_python[10,32+i] <- uni
}

ytm1 <- A1_python[,33:42]
year <- seq(0.5,5,0.5)
plot(year,t(ytm1[,1]),type = 'l', xlab = 'Year', ylab = 'spot rate', main = 'spot curve',col='red', ylim=c(0.013,0.021))
lines(year,t(ytm1[,2]),col=1,lty=1,type = 'l')
lines(year,t(ytm1[,3]),col=2,lty=1,type = 'l')
lines(year,t(ytm1[,4]),col=3,lty=1,type = 'l')
lines(year,t(ytm1[,5]),col=4,lty=1,type = 'l')
lines(year,t(ytm1[,6]),col=5,lty=1,type = 'l')
lines(year,t(ytm1[,7]),col=6,lty=1,type = 'l')
lines(year,t(ytm1[,8]),col=7,lty=1,type = 'l')
lines(year,t(ytm1[,9]),col=8,lty=1,type = 'l')
lines(year,t(ytm1[,10]),col=9,lty=1,type = 'l')
```


```{r}
# forward 1-1
frate <- data.frame()
forwdata <- A1_python[,33:43]
for (i in 1:10){
  frate[1,i] <- 4*as.numeric(forwdata[4,i])-2*as.numeric(forwdata[2,i])
}

# forward 1-2
for (i in 1:10){
  frate[2,i] <- (6*as.numeric(forwdata[6,i])-2*as.numeric(forwdata[2,i]))/2
}

# forward 1-3
for (i in 1:10){
  frate[3,i] <- (8*as.numeric(forwdata[8,i])-2*as.numeric(forwdata[2,i]))/3
}

# forward 1-4
for (i in 1:10){
  frate[4,i] <- (10*as.numeric(forwdata[10,i])-2*as.numeric(forwdata[2,i]))/4
}

# plot the forward rates for different dates
plot(c(1,2,3,4), frate[,1], type = 'l',main = "1-Year Deferred Forward Curve", xlab = "years forward", ylab = "Forward Rate", ylim = c(0.025,0.033))
lines(c(1,2,3,4), frate[,2],type = 'l',lwd = 1.0, col='red')
lines(c(1,2,3,4), frate[,3],type = 'l',lwd = 1.0, col='green')
lines(c(1,2,3,4), frate[,4],type = 'l',lwd = 1.0, col='blue')
lines(c(1,2,3,4), frate[,5],type = 'l',lwd = 1.0, col='lightblue')
lines(c(1,2,3,4), frate[,6],type = 'l',lwd = 1.0, col='brown')
lines(c(1,2,3,4), frate[,7],type = 'l',lwd = 1.0, col='orange')
lines(c(1,2,3,4), frate[,8],type = 'l',lwd = 1.0, col='grey')
lines(c(1,2,3,4), frate[,9],type = 'l',lwd = 1.0, col='darkblue')
lines(c(1,2,3,4), frate[,10],type = 'l',lwd = 1.0, col='yellowgreen')
```




```{r}
ytm1 <- A1_python[,22:31]
x1 <- vector("numeric", 9)
x2 <- vector("numeric", 9)
x3 <- vector("numeric", 9)
x4 <- vector("numeric", 9)
x5 <- vector("numeric", 9)
for (i in c(0:8)){
  x1[i] <- log(as.numeric(ytm1[2,i])/as.numeric(ytm1[2,i+1]))
  x2[i] <- log(as.numeric(ytm1[4,i])/as.numeric(ytm1[4,i+1]))
  x3[i] <- log(as.numeric(ytm1[6,i])/as.numeric(ytm1[6,i+1]))
  x4[i] <- log(as.numeric(ytm1[8,i])/as.numeric(ytm1[8,i+1]))
  x5[i] <- log(as.numeric(ytm1[10,i])/as.numeric(ytm1[10,i+1]))
}
return <- data.frame(x1,x2,x3,x4,x5)
yield_cov <- cov(return, return)


```


```{r}

forward_rate <- t(frate)
x1=x2=x3=vector("numeric")
for (i in 1:9){
  x1[i]=log(forward_rate[i,2]/forward_rate[i,1])
  x2[i]=log(forward_rate[i,3]/forward_rate[i,2])
  x3[i]=log(forward_rate[i,4]/forward_rate[i,3])
}
logretfwds=data.frame(x1,x2,x3,x4)
covm2=cov(logretfwds,logretfwds)

ei <- eigen(yield_cov)
ei$values
ei$vectors
ei$vectors[,1]*ei$values[1]

ei <- eigen(covm2)
ei$values
ei$vectors
ei$vectors[,1]*ei$values[1]
```




